publisher_node:
  ros__parameters:
    topic_name: "num_topic"
    publish_rate: 2.0

subscriber_node:
  ros__parameters:
    topic_name: "num_topic"
    yolo_topic_name: "result_img"

service_node:
  ros__parameters:
    service_name: "yolo"
    yolo_topic_name: "result_img"

client_node:
  ros__parameters:
    client_name: "yolo"

tf2_publisher:
  ros__parameters:
    frame_id: "base_link1"
    child_frame_id: "camera_link1"

tf2_listener:
  ros__parameters:
    frame_id: "base_link1"
    child_frame_id: "camera_link1"